### ISSUE TITLE
Pin generator script isn't called by yt test

### ISSUE THREAD

**Issue by akselsm** [ARMmbed/mbed-hal#25]
I'm a bit unsure whether this belongs here or in yotta, but anyway:

Calling yt test initiates a build if the files are out of date. However, it does not seem to generate the pins.array file, causing the build to fail (missing include). If yt build is called before yt test, the pins.array exists from the previous run, and the compilation succeeds.

How to reproduce: Call yt clean && yt test all (or similar).

@0xc0170 @bremoran

**Comment by bremoran** [comment]
cc @autopulated

**Comment by autopulated** [comment]
Ah, I'm guessing this is because `yotta test` doesn't build the CMake "ALL" target, and the pins stuff is generated by a rule hooked off all?

I'll have a look at the rules used to generate the pins file and see if I can come up with anything better.

**Comment by bremoran** [comment]
Yes, that's right, I hooked the ALL target.

**Comment by autopulated** [comment]
Please try this: https://github.com/ARMmbed/mbed-hal/pull/26

**Comment by bremoran** [comment]
I hooked ALL in mbed-hal.  Unless you're doing this *in* mbed-hal, it should still call the ALL target, no?

**Comment by bremoran** [comment]
#26 looks about right to me, @autopulated

**Comment by autopulated** [comment]
@bremoran yotta test does the equivalent of `make testexe-1 testexe-2 testexe-3`, which is explicitly not building ALL, (but mbed-hal will be an indirect dependency of each test executable, so will still get built).

**Comment by 0xc0170** [comment]
@akselsm Please test and close this PR if fixed.
