### ISSUE TITLE
Check if the new I2C_EVENT_TRANSFER_EARLY_NACK is correct

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/mbed-hal#4]
This relates to PR #3: the new ```I2C_EVENT_TRANSFER_EARLY_NACK``` flag might be K64F specific and not present on other I2C controllers on other targets; if this is the case, this needs a different fix.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-882

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1010
