### ISSUE TITLE
Build break due to dma_api.h not included in i2c_api.h

### ISSUE THREAD

**Issue by bangaragirinxp** [ARMmbed/mbed-hal#65]
Hi,

  When example-async-i2c application is built for JN5179 platform, the build is breaking because dma_api.h file is not included in i2c_api.h. Please find the error logs & script which will clone the required components & build the example (Rename the script example_async_i2c.txt to example_async_i2c.bat & use it).

With kind regards,
Giri
[log.txt](https://github.com/ARMmbed/mbed-hal/files/82395/log.txt)
[example_async_i2c.txt](https://github.com/ARMmbed/mbed-hal/files/82396/example_async_i2c.txt)

**Comment by 0xc0170** [comment]
Thanks for reporting, I'll look at mbed-drivers and mbed-hal , will report back

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1723
